name: cpx_research_sdk_flutter
description: CPX Research SDK Flutter
version: 0.4.5
homepage: https://www.makeopinion.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  webview_flutter: ^4.9.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  json_serializable: ^6.6.1